name: .NET Core

on:
  push:
    branches: [ ci_cd ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install Dependencies
      working-directory: src/Configuratorr
      run: dotnet restore
    - name: Build
      working-directory: src/Configuratorr
      run: dotnet build --configuration Release --no-restore
    - name: Test
      working-directory: test/ConfiguratorrTests
      run: dotnet restore && dotnet test --no-restore --verbosity normal
